TV_SHOW = 'StrangerThings'
OUT_DIR = '../tvshows/output/'
GAMMA = 0.2
TOLERANCE = 1e-6
ITERATIONS = 100
NUM_TOPICS = 10
PRE_PROCESSED_FILE_NAME = 'StrangerThings'
LDA_FILE_NAME = 'StrangerThings'
GRAPHML_FILE = 'StrangerThings.graphml'
TOPIC_VEC_FILE = 'StrangerThings_topic_frame.csv'
TWITTER_RANK_FILE = 'StrangerThings_topic_rank_frame.csv'
GRAPH_NODE_FILE = 'StrangerThings_graph_nodes_with_no_isolated_nodes.csv'
NUM_OF_INFLUENTIAL_NODES = 20


# TV_SHOW = 'ThisIsUS'
# OUT_DIR = '../tvshows/output/'
# GAMMA = 0.2
# TOLERANCE = 1e-6
# ITERATIONS = 100
# NUM_TOPICS = 10
# PRE_PROCESSED_FILE_NAME = 'old_tweets'
# LDA_FILE_NAME = 'old_tweets'
# GRAPHML_FILE = 'ThisIsUs.graphml'
# TOPIC_VEC_FILE = 'topic_frame.csv'
# TWITTER_RANK_FILE = 'topic_rank_frame.csv'
# GRAPH_NODE_FILE = 'graph_nodes.csv'
# LDA_FILE_NAME = 'old_tweets'
# NUM_OF_INFLUENTIAL_NODES = 10

# TV_SHOW = 'TheGoodPlace'
# OUT_DIR = '../tvshows/output/'
# GAMMA = 0.2
# TOLERANCE = 1e-6
# ITERATIONS = 100
# NUM_TOPICS = 10
# PRE_PROCESSED_FILE_NAME = 'old_tweets'
# LDA_FILE_NAME = 'old_tweets'
# GRAPHML_FILE = 'TheGoodPlace.graphml'
# TOPIC_VEC_FILE = 'topic_frame.csv'
# TWITTER_RANK_FILE = 'topic_rank_frame.csv'
# GRAPH_NODE_FILE = 'TheGoodPlace_graph_nodes_with_no_isolated_nodes.csv'
# LDA_FILE_NAME = 'old_tweets'
# NUM_OF_INFLUENTIAL_NODES = 10