TV_SHOW = 'StrangerThings'
DB_NAME = 'tweetCorpus'
STREAM_COLL = 'stream_tweets'
HIST_COLL = 'historical_tweets2'
NODE_GRAPH = './output/'+TV_SHOW+'.graphml'
LOG_FILE = './output/'+TV_SHOW+'_retweetNetwork.log'
DATA = 'HISTORICAL_DATA'